In [1]:

import numpy as np
import pandas as pd

m1=np.arange(16).reshape(4,4)
print(m1)

df1=pd.DataFrame(m1,index=['r1','r2','r3','r4'],columns=['c1','c2','c3','c4'])
df1.index.name='i1'
df1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


c1  c2  c3  c4
i1                
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15

In [4]:

m1=np.arange(100,116).reshape(4,4)
print(m1)

df2=pd.DataFrame(m1,index=['r1','r2','r3','r4'],columns=['c5','c6','c7','c8'])
df2.index.name='i1'
df2

[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]]


c5   c6   c7   c8
i1                    
r1  100  101  102  103
r2  104  105  106  107
r3  108  109  110  111
r4  112  113  114  115

In [5]:
pd.merge(df1,df2,on='i1')

c1  c2  c3  c4   c5   c6   c7   c8
i1                                    
r1   0   1   2   3  100  101  102  103
r2   4   5   6   7  104  105  106  107
r3   8   9  10  11  108  109  110  111
r4  12  13  14  15  112  113  114  115