In [1]:

import numpy as np
import pandas as pd

m1=np.arange(16).reshape(4,4)
print(m1)

df1=pd.DataFrame(m1,index=['r1','r2','r3','r4'],columns=['c1','c2','c3','c4'])
df1.index.name='i1'
df1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


c1  c2  c3  c4
i1                
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15

In [6]:

m1=np.arange(100,116).reshape(4,4)
print(m1)

df2=pd.DataFrame(m1,index=['r1','r2','r3','r5'],columns=['c5','c6','c7','c8'])
df2.index.name='i1'
df2

[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]]


c5   c6   c7   c8
i1                    
r1  100  101  102  103
r2  104  105  106  107
r3  108  109  110  111
r5  112  113  114  115

In [10]:
pd.merge(df1,df2,on='i1',how='outer')

c1    c2    c3    c4     c5     c6     c7     c8
i1                                                    
r1   0.0   1.0   2.0   3.0  100.0  101.0  102.0  103.0
r2   4.0   5.0   6.0   7.0  104.0  105.0  106.0  107.0
r3   8.0   9.0  10.0  11.0  108.0  109.0  110.0  111.0
r4  12.0  13.0  14.0  15.0    NaN    NaN    NaN    NaN
r5   NaN   NaN   NaN   NaN  112.0  113.0  114.0  115.0

In [11]:
m1=np.arange(100,116).reshape(4,4)
df5=pd.DataFrame(m1,index=['r1','r2','r3','r4'],columns=['c1','c2','c3','c4'])
# df5.index.name='i1'
df5

c1   c2   c3   c4
r1  100  101  102  103
r2  104  105  106  107
r3  108  109  110  111
r4  112  113  114  115

In [12]:
m1=np.arange(16).reshape(4,4)

df6=pd.DataFrame(m1,index=['r5','r6','r7','r8'],columns=['c1','c2','c3','c4'])
# df6.index.name='i1'
df6

c1  c2  c3  c4
r5   0   1   2   3
r6   4   5   6   7
r7   8   9  10  11
r8  12  13  14  15

In [13]:
pd.concat([df5,df6])

c1   c2   c3   c4
r1  100  101  102  103
r2  104  105  106  107
r3  108  109  110  111
r4  112  113  114  115
r5    0    1    2    3
r6    4    5    6    7
r7    8    9   10   11
r8   12   13   14   15

In [15]:
data1=pd.read_html('https://www.screener.in/screens/281185/nifty-50/')[0]
data1

S.No.              Name  CMP  Rs.    P/E  Mar Cap  Rs.Cr.  Div Yld  %  \
0      1.  Reliance Industr   1518.90  26.82       2055446.70        0.36   
1      2.         HDFC Bank    989.60  21.03       1521677.59        1.11   
2      3.     Bharti Airtel   2100.70  39.13       1259903.13        0.76   
3      4.               TCS   3106.00  22.35       1123777.98        1.93   
4      5.        ICICI Bank   1373.00  18.41        981160.51        0.80   
5      6.               SBI    967.85  11.37        893385.32        1.64   
6      7.     Bajaj Finance   1018.50  34.63        633759.78        0.43   
7      8.           Infosys   1502.80  22.20        624323.43        2.86   
8      9.    Life Insurance    909.45  11.26        575226.92        1.32   
9     10.    Hind. Unilever   2427.70  53.92        570410.27        1.77   
10    11.   Larsen & Toubro   4004.40  34.27        550837.60        0.85   
11    12.               ITC    408.15  25.35        511323.69        3.52   
12    13.     Maruti Suzuki  15684.00  33.36        493109.00        0.86   
13    14.             M & M   3698.60  32.32        459931.57        0.68   
14    15.  HCL Technologies   1594.60  25.49        432721.04        3.39   
15  S.No.              Name  CMP  Rs.    P/E  Mar Cap  Rs.Cr.  Div Yld  %   
16    16.  Sun Pharma.Inds.   1757.10  36.52        421587.15        0.91   
17    17.   Kotak Mah. Bank   2079.70  22.27        413575.40        0.12   
18    18.         Axis Bank   1241.60  14.83        385332.49        0.08   
19    19.    UltraTech Cem.  11874.00  47.70        349902.05        0.65   
20    20.     Titan Company   3829.20  82.33        339951.08        0.29   
21    21.     Bajaj Finserv   2065.80  34.10        330076.25        0.05   
22    22.       Adani Ports   1512.70  27.23        326764.22        0.46   
23    23.              NTPC    328.45  13.41        318487.00        2.54   
24    24.  Hind.Aeronautics   4729.80  37.35        316317.20        0.85   
25    25.   Bharat Electron    426.85  54.78        312017.91        0.56   

    NP Qtr  Rs.Cr.  Qtr Profit Var  %  Sales Qtr  Rs.Cr.  Qtr Sales Var  %  \
0         22092.00               9.67          254623.00              9.97   
1         20363.77              10.01           86993.84              4.81   
2          8650.80              65.11           52145.40             25.73   
3         12131.00               8.54           65799.00              2.40   
4         14318.15               3.16           48180.91              4.00   
5         21860.59              -4.25          128040.50              5.78   
6          4947.76              21.89           20178.90             18.06   
7          7375.00              13.19           44490.00              8.55   
8         10095.92              30.66          241524.29              4.50   
9          2694.00              -2.14           16241.00              1.98   
10         4678.01              15.63           67983.53             10.44   
11         5186.55               2.91           19501.63             -2.44   
12         3349.00               7.95           42344.20             13.07   
13         3963.75              15.85           46105.67             21.57   
14         4236.00               0.00           31942.00             10.67   
15  NP Qtr  Rs.Cr.  Qtr Profit Var  %  Sales Qtr  Rs.Cr.  Qtr Sales Var  %   
16         3124.95               2.56           14478.31              8.93   
17         4468.27             -11.42           17198.74              4.70   
18         5566.56             -25.31           32309.77              2.24   
19         1237.98              75.23           19606.93             20.33   
20         1120.00              59.09           18725.00             28.84   
21         4746.47               7.53           37402.93             10.98   
22         3120.20              25.07            9167.46             29.72   
23         5225.30              -3.94           4478

In [16]:
data2=pd.read_html('https://www.screener.in/market/IN05/IN0501/IN050102/')[0]
data2

S.No.              Name  CMP  Rs.    P/E  Mar Cap  Rs.Cr.  Div Yld  %  \
0      1.         HDFC Bank    989.60  21.03       1521677.59        1.11   
1      2.        ICICI Bank   1373.00  18.41        981160.51        0.80   
2      3.               SBI    967.85  11.37        893385.32        1.64   
3      4.   Kotak Mah. Bank   2079.70  22.27        413575.40        0.12   
4      5.         Axis Bank   1241.60  14.83        385332.49        0.08   
5      6.    Bank of Baroda    286.75   7.71        148288.81        2.91   
6      7.  Punjab Natl.Bank    122.21   8.24        140455.26        2.37   
7      8.       Canara Bank    146.07   6.92        132495.00        2.74   
8      9.       Indian Bank    868.45   9.93        116977.09        1.87   
9     10.    Union Bank (I)    152.76   6.31        116610.96        3.11   
10    11.         IDBI Bank    101.04  11.70        108642.27        2.08   
11    12.             I O B     38.79  17.53         74696.31        0.00   
12    13.          Yes Bank     22.50  24.88         70594.62        0.00   
13    14.   IDFC First Bank     80.43  48.09         69114.23        0.31   
14    15.     Bank of India    146.52   6.66         66705.69        2.76   
15  S.No.              Name  CMP  Rs.    P/E  Mar Cap  Rs.Cr.  Div Yld  %   
16    16.  AU Small Finance    890.60  30.58         66469.82        0.11   
17    17.     IndusInd Bank    848.25    NaN         66085.12        0.00   
18    18.      Federal Bank    236.26  14.73         58124.21        0.51   
19    19.      Bank of Maha     58.01   7.33         44618.71        2.59   
20    20.          UCO Bank     30.72  15.30         38521.53        1.27   
21    21.      Central Bank     37.91   7.58         34313.86        1.06   
22    22.      Bandhan Bank    154.59  20.28         24904.01        0.97   
23    23.  Karur Vysya Bank    249.60  11.46         24117.58        0.87   
24    24.  Pun. & Sind Bank     30.14  18.46         21386.09        0.23   
25    25.   City Union Bank    270.59  16.59         20052.04        0.74   

    NP Qtr  Rs.Cr.  Qtr Profit Var  %  Sales Qtr  Rs.Cr.  Qtr Sales Var  %  \
0         20363.77              10.01           86993.84              4.81   
1         14318.15               3.16           48180.91              4.00   
2         21860.59              -4.25          128040.50              5.78   
3          4468.27             -11.42           17198.74              4.70   
4          5566.56             -25.31           32309.77              2.24   
5          5180.63              -4.14           33318.24              4.44   
6          5120.59               8.72           32512.76              6.78   
7          4896.43              15.81           32071.97              6.26   
8          3108.63              11.01           16628.28              8.19   
9          4425.95              -6.84           26664.81             -0.82   
10         3240.77              73.56            7109.01             -4.51   
11         1226.42              57.81            7848.79             14.57   
12          664.31              17.25            7388.75             -4.50   
13          347.80              64.10            9936.93             10.94   
14         2575.58               6.42           18521.48              6.04   
15  NP Qtr  Rs.Cr.  Qtr Profit Var  %  Sales Qtr  Rs.Cr.  Qtr Sales Var  %   
16          560.87              -1.81            4511.28             15.36   
17         -436.88            -132.82           11608.63             -8.49   
18         1022.64              -9.52            7216.18              3.00   
19         1668.61              25.20            7128.36             18.46   
20          619.76               2.82            6537.17              7.55   
21         1234.06              33.34            8776.54              6.57   
22          111.87             -88.07            5353.83             -2.65   
23          573.96              21.19            280

In [17]:
pd.concat([data1,data2])

S.No.              Name  CMP  Rs.    P/E  Mar Cap  Rs.Cr.  Div Yld  %  \
0      1.  Reliance Industr   1518.90  26.82       2055446.70        0.36   
1      2.         HDFC Bank    989.60  21.03       1521677.59        1.11   
2      3.     Bharti Airtel   2100.70  39.13       1259903.13        0.76   
3      4.               TCS   3106.00  22.35       1123777.98        1.93   
4      5.        ICICI Bank   1373.00  18.41        981160.51        0.80   
5      6.               SBI    967.85  11.37        893385.32        1.64   
6      7.     Bajaj Finance   1018.50  34.63        633759.78        0.43   
7      8.           Infosys   1502.80  22.20        624323.43        2.86   
8      9.    Life Insurance    909.45  11.26        575226.92        1.32   
9     10.    Hind. Unilever   2427.70  53.92        570410.27        1.77   
10    11.   Larsen & Toubro   4004.40  34.27        550837.60        0.85   
11    12.               ITC    408.15  25.35        511323.69        3.52   
12    13.     Maruti Suzuki  15684.00  33.36        493109.00        0.86   
13    14.             M & M   3698.60  32.32        459931.57        0.68   
14    15.  HCL Technologies   1594.60  25.49        432721.04        3.39   
15  S.No.              Name  CMP  Rs.    P/E  Mar Cap  Rs.Cr.  Div Yld  %   
16    16.  Sun Pharma.Inds.   1757.10  36.52        421587.15        0.91   
17    17.   Kotak Mah. Bank   2079.70  22.27        413575.40        0.12   
18    18.         Axis Bank   1241.60  14.83        385332.49        0.08   
19    19.    UltraTech Cem.  11874.00  47.70        349902.05        0.65   
20    20.     Titan Company   3829.20  82.33        339951.08        0.29   
21    21.     Bajaj Finserv   2065.80  34.10        330076.25        0.05   
22    22.       Adani Ports   1512.70  27.23        326764.22        0.46   
23    23.              NTPC    328.45  13.41        318487.00        2.54   
24    24.  Hind.Aeronautics   4729.80  37.35        316317.20        0.85   
25    25.   Bharat Electron    426.85  54.78        312017.91        0.56   
0      1.         HDFC Bank    989.60  21.03       1521677.59        1.11   
1      2.        ICICI Bank   1373.00  18.41        981160.51        0.80   
2      3.               SBI    967.85  11.37        893385.32        1.64   
3      4.   Kotak Mah. Bank   2079.70  22.27        413575.40        0.12   
4      5.         Axis Bank   1241.60  14.83        385332.49        0.08   
5      6.    Bank of Baroda    286.75   7.71        148288.81        2.91   
6      7.  Punjab Natl.Bank    122.21   8.24        140455.26        2.37   
7      8.       Canara Bank    146.07   6.92        132495.00        2.74   
8      9.       Indian Bank    868.45   9.93        116977.09        1.87   
9     10.    Union Bank (I)    152.76   6.31        116610.96        3.11   
10    11.         IDBI Bank    101.04  11.70        108642.27        2.08   
11    12.             I O B     38.79  17.53         74696.31        0.00   
12    13.          Yes Bank     22.50  24.88         70594.62        0.00   
13    14.   IDFC First Bank     80.43  48.09         69114.23        0.31   
14    15.     Bank of India    146.52   6.66         66705.69        2.76   
15  S.No.              Name  CMP  Rs.    P/E  Mar Cap  Rs.Cr.  Div Yld  %   
16    16.  AU Small Finance    890.60  30.58         66469.82        0.11   
17    17.     IndusInd Bank    848.25    NaN         66085.12        0.00   
18    18.      Federal Bank    236.26  14.73         58124.21        0.51   
19    19.      Bank of Maha     58.01   7.33         44618.71        2.59   
20    20.          UCO Bank     30.72  15.30         38521.53        1.27   
21    21.      Central Bank     37.91   7.58         34313.86        1.06   
22    22.      Bandhan Bank    154.59  20.28         24904.01        0.97   
23    23.  Karur Vysya Bank    249.60  11.46         24117.58        0.87   
24    24.  Pun. & Sind Bank     30.14  18.46         21386.09        0.23   


In [19]:
data1.set_index("Name",inplace=True)
data2.set_index("Name",inplace=True)
data1

S.No.  CMP  Rs.    P/E  Mar Cap  Rs.Cr.  Div Yld  %  \
Name                                                                    
Reliance Industr     1.   1518.90  26.82       2055446.70        0.36   
HDFC Bank            2.    989.60  21.03       1521677.59        1.11   
Bharti Airtel        3.   2100.70  39.13       1259903.13        0.76   
TCS                  4.   3106.00  22.35       1123777.98        1.93   
ICICI Bank           5.   1373.00  18.41        981160.51        0.80   
SBI                  6.    967.85  11.37        893385.32        1.64   
Bajaj Finance        7.   1018.50  34.63        633759.78        0.43   
Infosys              8.   1502.80  22.20        624323.43        2.86   
Life Insurance       9.    909.45  11.26        575226.92        1.32   
Hind. Unilever      10.   2427.70  53.92        570410.27        1.77   
Larsen & Toubro     11.   4004.40  34.27        550837.60        0.85   
ITC                 12.    408.15  25.35        511323.69        3.52   
Maruti Suzuki       13.  15684.00  33.36        493109.00        0.86   
M & M               14.   3698.60  32.32        459931.57        0.68   
HCL Technologies    15.   1594.60  25.49        432721.04        3.39   
Name              S.No.  CMP  Rs.    P/E  Mar Cap  Rs.Cr.  Div Yld  %   
Sun Pharma.Inds.    16.   1757.10  36.52        421587.15        0.91   
Kotak Mah. Bank     17.   2079.70  22.27        413575.40        0.12   
Axis Bank           18.   1241.60  14.83        385332.49        0.08   
UltraTech Cem.      19.  11874.00  47.70        349902.05        0.65   
Titan Company       20.   3829.20  82.33        339951.08        0.29   
Bajaj Finserv       21.   2065.80  34.10        330076.25        0.05   
Adani Ports         22.   1512.70  27.23        326764.22        0.46   
NTPC                23.    328.45  13.41        318487.00        2.54   
Hind.Aeronautics    24.   4729.80  37.35        316317.20        0.85   
Bharat Electron     25.    426.85  54.78        312017.91        0.56   

                  NP Qtr  Rs.Cr.  Qtr Profit Var  %  Sales Qtr  Rs.Cr.  \
Name                                                                     
Reliance Industr        22092.00               9.67          254623.00   
HDFC Bank               20363.77              10.01           86993.84   
Bharti Airtel            8650.80              65.11           52145.40   
TCS                     12131.00               8.54           65799.00   
ICICI Bank              14318.15               3.16           48180.91   
SBI                     21860.59              -4.25          128040.50   
Bajaj Finance            4947.76              21.89           20178.90   
Infosys                  7375.00              13.19           44490.00   
Life Insurance          10095.92              30.66          241524.29   
Hind. Unilever           2694.00              -2.14           16241.00   
Larsen & Toubro          4678.01              15.63           67983.53   
ITC                      5186.55               2.91           19501.63   
Maruti Suzuki            3349.00               7.95           42344.20   
M & M                    3963.75              15.85           46105.67   
HCL Technologies         4236.00               0.00           31942.00   
Name              NP Qtr  Rs.Cr.  Qtr Profit Var  %  Sales Qtr  Rs.Cr.   
Sun Pharma.Inds.         3124.95               2.56           14478.31   
Kotak Mah. Bank          4468.27             -11.42           17198.74   
Axis Bank                5566.56             -25.31           32309.77   
UltraTech Cem.           1237.98              75.23           19606.93   
Titan Company            1120.00              59.09           18725.00   
Bajaj Finserv            4746.47               7.53           37402.93   
Adani Ports              3120.20              25.07            9167.46   
NTPC                     5225.30              -3.94           44785.82   
Hind.Aeronautics         1669.05              10.

In [21]:
df9=pd.merge(data1,data1,on='Name',how='outer')

In [23]:
df9.drop('Name',axis=0)

S.No._x CMP  Rs._x  P/E_x Mar Cap  Rs.Cr._x Div Yld  %_x  \
Name                                                                        
Adani Ports          22.    1512.70  27.23         326764.22         0.46   
Axis Bank            18.    1241.60  14.83         385332.49         0.08   
Bajaj Finance         7.    1018.50  34.63         633759.78         0.43   
Bajaj Finserv        21.    2065.80  34.10         330076.25         0.05   
Bharat Electron      25.     426.85  54.78         312017.91         0.56   
Bharti Airtel         3.    2100.70  39.13        1259903.13         0.76   
HCL Technologies     15.    1594.60  25.49         432721.04         3.39   
HDFC Bank             2.     989.60  21.03        1521677.59         1.11   
Hind. Unilever       10.    2427.70  53.92         570410.27         1.77   
Hind.Aeronautics     24.    4729.80  37.35         316317.20         0.85   
ICICI Bank            5.    1373.00  18.41         981160.51         0.80   
ITC                  12.     408.15  25.35         511323.69         3.52   
Infosys               8.    1502.80  22.20         624323.43         2.86   
Kotak Mah. Bank      17.    2079.70  22.27         413575.40         0.12   
Larsen & Toubro      11.    4004.40  34.27         550837.60         0.85   
Life Insurance        9.     909.45  11.26         575226.92         1.32   
M & M                14.    3698.60  32.32         459931.57         0.68   
Maruti Suzuki        13.   15684.00  33.36         493109.00         0.86   
NTPC                 23.     328.45  13.41         318487.00         2.54   
Reliance Industr      1.    1518.90  26.82        2055446.70         0.36   
SBI                   6.     967.85  11.37         893385.32         1.64   
Sun Pharma.Inds.     16.    1757.10  36.52         421587.15         0.91   
TCS                   4.    3106.00  22.35        1123777.98         1.93   
Titan Company        20.    3829.20  82.33         339951.08         0.29   
UltraTech Cem.       19.   11874.00  47.70         349902.05         0.65   

                 NP Qtr  Rs.Cr._x Qtr Profit Var  %_x Sales Qtr  Rs.Cr._x  \
Name                                                                        
Adani Ports               3120.20               25.07             9167.46   
Axis Bank                 5566.56              -25.31            32309.77   
Bajaj Finance             4947.76               21.89            20178.90   
Bajaj Finserv             4746.47                7.53            37402.93   
Bharat Electron           1287.16               17.88             5792.09   
Bharti Airtel             8650.80               65.11            52145.40   
HCL Technologies          4236.00                0.00            31942.00   
HDFC Bank                20363.77               10.01            86993.84   
Hind. Unilever            2694.00               -2.14            16241.00   
Hind.Aeronautics          1669.05               10.82             6628.61   
ICICI Bank               14318.15                3.16            48180.91   
ITC                       5186.55                2.91            19501.63   
Infosys                   7375.00               13.19            44490.00   
Kotak Mah. Bank           4468.27              -11.42            17198.74   
Larsen & Toubro           4678.01               15.63            67983.53   
Life Insurance           10095.92               30.66           241524.29   
M & M                     3963.75               15.85            46105.67   
Maruti Suzuki             3349.00                7.95            42344.20   
NTPC                      5225.30               -3.94            44785.82   
Reliance Industr         22092.00                9.67           254623.00   
SBI                      21860.59               -4.25           128040.50   
Sun Pharma.Inds.          3124.95                2.56            14478.31   
TCS                      12131.00                8.54            65799.00   
Titan Compan